### PR TITLE
Workflow to automatically update Encore's checksums when version.txt file is modified

### PR DESCRIPTION
**Pull request by luisnquin**
It would be good if you update that `version.txt` file when a new release is supplied by the CloudFront distribution. :)

### CODE REVIEW

**Comment by luisnquin** [comment]
@fredr FYI

**Comment by fredr** [comment]
Thanks! 

We already have a setup for this automation in our release flow, it just hasn't been released yet. I'll ping you here when it is released and ready

**Comment by luisnquin** [comment]
I really hope this comes soon. :)

**Comment by fredr** [comment]
Its now hooked up so that this repo will be updated for each new version :rocket:

**Pull request closed without merging**
